package roshambo.common;

import java.util.Random;

/**
 * One of the opponents in the Roshambo game.
 * Lisa generates a random hand for each round of the game.
 * Valid hands generated by Lisa are Rock, Paper or Scissors.
 * @author Steve Teece
 * @version 1.0
 */
public class Lisa extends Player
{
	
	/**
	 * Creates a new instance of Lisa, and assigns a randomly generated 
	 * Roshambo value of either Rock, Paper or Scissors.
	 */
	public Lisa()
	{
		this._name = "Lisa";
		this._selection = generateRoshambo();
	}

	@Override 
	Roshambo generateRoshambo() 
	{
		// Reference: https://kodejava.org/how-do-i-pick-a-random-value-from-an-enum/
		
		Random random = new Random();
        return Roshambo.values()[random.nextInt(Roshambo.values().length)];
}
	
	
}
